jobs:
  build:
    docker:
      - image: node:16.17.0
    environment: 
      COVERALLS_REPO_TOKEN: qyL7VHpxdSYwaWsAhyNjePEGUWcmSegos
  
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
          notify:
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info